apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ubeeq
resources:
  - namespace.yaml
  - configmap.yaml
  - api.yaml
  - worker.yaml
  - service.yaml
  - web.yaml
  - admin.yaml
  - ingress.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/ubeeq/ubeeq-reference
    newTag: REPLACE_WITH_RELEASED_IMAGE_TAG
