import { createServer } from "node:http";

const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ubeeq reference operations</title><style>body{font:16px system-ui,sans-serif;max-width:62rem;margin:2rem auto;padding:0 1rem}section{border:1px solid #ccd3da;border-radius:.5rem;padding:1rem;margin:1rem 0}input,select,button{font:inherit;padding:.4rem;margin:.2rem}pre{white-space:pre-wrap;background:#f4f6f7;padding:1rem;overflow:auto}.row{display:flex;gap:.4rem;align-items:center;flex-wrap:wrap}</style><body><h1>Ubeeq reference operations</h1><p>Plain reviewer, recovery, and diagnostics controls. A production deployment supplies its own authorization extension, review policy, and escalation workflow.</p><section><label>Session token <input id="token" size="52"></label><button id="diagnostics">Diagnostics</button></section><section><h2>Jobs and recovery</h2><button id="jobs">List jobs</button><button id="run">Run next</button><label>Job ID <input id="jobId"></label><button id="recover">Recover</button><button id="cancel">Cancel</button></section><section><h2>Moderation holds</h2><button id="holds">List holds</button><div class="row"><input id="holdType" placeholder="subject type" value="work"><input id="holdSubject" placeholder="subject id"><input id="holdReason" placeholder="neutral reason"><button id="createHold">Create hold</button></div><div class="row"><input id="holdId" placeholder="hold id"><button id="releaseHold">Release hold</button></div></section><section><h2>Review cases</h2><button id="cases">List cases</button><div class="row"><input id="caseSubject" placeholder="subject id"><button id="createCase">Open case</button></div><div class="row"><input id="caseId" placeholder="case id"><select id="caseState"><option>open</option><option>assigned</option><option>decided</option><option>closed</option></select><input id="assignee" placeholder="assignee id"><button id="updateCase">Update case</button></div></section><section><h2>Evidence and audit</h2><button id="evidence">Moderation evidence</button><button id="audit">Audit events</button><button id="usage">Usage events</button></section><section><h2>Regional control plane</h2><p>Available only when this deployment supplies a managed directory and operator authorization requirement.</p><button id="routes">List routes</button><button id="migrations">List migrations</button><label>Migration ID <input id="migrationId"></label><button id="resume">Resume</button><button id="rollback">Rollback</button><button id="retire">Retire source</button></section><pre id="output" aria-live="polite">Ready.</pre><script>
const $=id=>document.getElementById(id),out=x=>$('output').textContent=typeof x==='string'?x:JSON.stringify(x,null,2),api=async(path,method='GET',body)=>{const r=await fetch('/api'+path,{method,headers:{'content-type':'application/json',authorization:'Bearer '+$('token').value},body:body?JSON.stringify(body):undefined}),v=r.status===204?null:await r.json();if(!r.ok)throw Error(v.error?.message||'Request failed');return v},bind=(id,path,method='GET',body)=>$(id).onclick=async()=>{try{out(await api(path,method,body?.()))}catch(e){out(e.message)}};
bind('diagnostics','/diagnostics');bind('jobs','/v1/operations/jobs');bind('run','/v1/operations/jobs/run-next','POST',()=>({workerId:'reference-operations'}));bind('recover','/v1/operations/jobs/'+$('jobId').value+'/recover','POST',()=>({}));bind('cancel','/v1/operations/jobs/'+$('jobId').value+'/cancel','POST',()=>({reason:'operator_cancelled'}));
bind('holds','/v1/operations/holds');bind('createHold','/v1/operations/holds','POST',()=>({subjectType:$('holdType').value,subjectId:$('holdSubject').value,reason:$('holdReason').value}));bind('releaseHold','/v1/operations/holds/'+$('holdId').value+'/release','POST',()=>({}));
bind('cases','/v1/operations/review-cases');bind('createCase','/v1/operations/review-cases','POST',()=>({subjectId:$('caseSubject').value}));bind('updateCase','/v1/operations/review-cases/'+$('caseId').value,'POST',()=>({state:$('caseState').value,assigneeId:$('assignee').value||undefined}));
bind('evidence','/v1/operations/moderation-evidence');bind('audit','/v1/operations/audit-events');bind('usage','/v1/operations/usage-events');bind('routes','/v1/operations/regional/routes');bind('migrations','/v1/operations/regional/migrations');bind('resume','/v1/operations/regional/migrations/'+$('migrationId').value+'/resume','POST',()=>({}));bind('rollback','/v1/operations/regional/migrations/'+$('migrationId').value+'/rollback','POST',()=>({}));bind('retire','/v1/operations/regional/migrations/'+$('migrationId').value+'/retire','POST',()=>({}));
</script></body></html>`;
const json=(response,status,body)=>{response.writeHead(status,{"content-type":"application/json; charset=utf-8"});response.end(JSON.stringify(body));};
export const createAdminReferenceApp=({referenceApiUrl=process.env.UBEEQ_REFERENCE_API_URL||"http://127.0.0.1:4100"}={})=>{const upstream=new URL(referenceApiUrl);return createServer(async(request,response)=>{const url=new URL(request.url||"/","http://admin.local");if(url.pathname==="/health")return json(response,200,{status:"ok"});if(url.pathname.startsWith("/api/")){try{const chunks=[];for await(const chunk of request)chunks.push(chunk);const target=new URL(url.pathname.slice(4)+url.search,upstream),headers={"content-type":request.headers["content-type"]||"application/json",...(request.headers.authorization?{authorization:request.headers.authorization}:{})};const result=await fetch(target,{method:request.method,headers,body:chunks.length?Buffer.concat(chunks):undefined});response.writeHead(result.status,{"content-type":result.headers.get("content-type")||"application/json"});response.end(Buffer.from(await result.arrayBuffer()));}catch{return json(response,502,{error:"reference_api_unavailable"});}return;}if(url.pathname==="/"||url.pathname==="/operations"){response.writeHead(200,{"content-type":"text/html; charset=utf-8"});response.end(html);return;}return json(response,404,{error:"not_found"});});};
if(import.meta.url===`file://${process.argv[1]}`){const port=Number(process.env.PORT||4174);createAdminReferenceApp().listen(port,"127.0.0.1",()=>console.log(`Ubeeq reference operations listening on http://127.0.0.1:${port}`));}
